services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: spam-classification-jupyter
    ports:
      - "8888:8888"
    volumes:
      - jupyter_data:/home/jovyan/.jupyter
      - jupyter_local:/home/jovyan/.local
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    command: >
      bash -c "chown -R jovyan:users /home/jovyan/.jupyter /home/jovyan/.local &&
               start-notebook.sh --IdentityProvider.token='' --ServerApp.password=''"

volumes:
  jupyter_data:
  jupyter_local:
